### ISSUE TITLE
More tile map providers

### ISSUE THREAD

**Issue by scls19fr** [JuliaGeo/MapTiles.jl#12]
Hello,

Following #5, a large number of online map providers can be found in
https://github.com/leaflet-extras/leaflet-providers/blob/master/leaflet-providers.js (JavaScript code)

or also in https://github.com/tumic0/GPXSee-maps (XML data with corresponding URL).

or in MOBAC
https://sourceforge.net/p/mobac/code/HEAD/tree/trunk/MOBAC/mapsources/ (Java code or BeanShell)
https://sourceforge.net/p/mobac/code/HEAD/tree/trunk/MOBAC/mappacks/

Maybe an approach could be to have this kind of data outside of Julia code but simply as data in a repository which could be shared accross several projects (in differents languages).

Any opinion about it?

Kind regards

**Comment by yeesian** [comment]
> Maybe an approach could be to have this kind of data outside of Julia code but simply as data in a repository which could be shared accross several projects (in differents languages).

I don't mind using depending on such a package if it exists and has a clear owner and maintainer in its roadmap. In the meantime, I don't mind sticking to the current approach.

**Comment by rafaqz** [comment]
I think we could combine the providers here with those in [Leaflet.jl](https://github.com/JuliaGeo/Leaflet.jl/blob/main/src/providers.jl) in a TileProviders.jl package.

This would also be useful in GeoMakie.jl: https://github.com/MakieOrg/GeoMakie.jl/issues/67

**Comment by rafaqz** [comment]
We now automatically parse the leaflet providers in TileProviders.jl, so closing this.
