### ISSUE TITLE
Get basemap that honors specified bounding box

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/MapTiles.jl#2]
I wonder if it would be possible to get a basemap that honors the specified lon/lat min/max pairs. Right now, when I plot the basemap, it includes extra "borders" that don't make a good visualization:

![screenshot from 2018-01-13 16-07-32](https://user-images.githubusercontent.com/3345261/34911266-e60e22ea-f87b-11e7-874b-2405d026320e.png)

Alternatively, if the basemap object stores the lon/lat min/max values, the plot recipe could crop the borders.

**Comment by juliohm** [comment]
I can plot it correctly by specifying `xlim` and `ylim` in the plot line, I think my question is more about why we keep the borders outside of the requested box?

**Comment by yeesian** [comment]
> I think my question is more about why we keep the borders outside of the requested box?

That's because Plots displays the entire tile by default. You can make it a plots recipe to set the xlim and ylim values accordingly.

**Comment by juliohm** [comment]
Maybe the plot recipe for the `BaseMap` type defined in the package could be adjusted?

**Comment by yeesian** [comment]
Yup. Will you like to give it a shot? You will need to pass the [input values](https://github.com/yeesian/MapTiles.jl/blob/master/src/MapTiles.jl#L33) through to the BaseMap for storage before you can access it in the [plotrecipe](https://github.com/yeesian/MapTiles.jl/blob/master/src/MapTiles.jl#L17-L23)

**Comment by juliohm** [comment]
I can give it a shot when I find time, but feel free to implement it if I
take too long ;)

**Comment by rafaqz** [comment]
Tyler.jl will handle this properly for Makie plots now.

**Comment by visr** [comment]
> Tyler.jl will handle this properly for Makie plots now.

Indeed, and since this package now only finds the appropriate tiles, I think it is out of scope.
