### ISSUE TITLE
add Stadia Maps as a provider

### ISSUE THREAD

**Issue by yeesian** [JuliaGeo/MapTiles.jl#5]
https://docs.stadiamaps.com/

**Comment by scls19fr** [comment]
Maybe it could be worth to split this package to have map providers outside of this repository.
But documenting how to create custom map provider should probably be done. (See https://github.com/yeesian/MapTiles.jl/issues/6#issuecomment-773102290 )

**Comment by yeesian** [comment]
> documenting how to create custom map provider should probably be done.

Yeah that'll be nice to have

**Comment by rafaqz** [comment]
TileProviders.jl has `Stadia`
